### ISSUE TITLE
Trajectories: Error in encoding/decoding

### ISSUE THREAD

**Issue by 4rzael** [anthill/pheromon-codecs#5]
When trying to encode + decode [this](https://gist.github.com/vallettea/d6b12129e2847df62fed#file-gistfile1-txt), pheromon-codecs throws this error:

```
     Error: Groups are not supported
      at skip (node_modules/protocol-buffers/compile.js:21:11)
      at Object.decode (eval at <anonymous> (node_modules/protocol-buffers/node_modules/generate-function/index.js:55:21), <anonymous>:34:16)
      at Object.decode (eval at <anonymous> (node_modules/protocol-buffers/node_modules/generate-function/index.js:55:21), <anonymous>:26:38)
      at trajectories/decode.js:17:50
      at new Promise (node_modules/es6-shim/es6-shim.js:1759:9)
      at Object.decode (trajectories/decode.js:16:12)
      at tests/trajectories/general-test.js:196:34
      at node_modules/es6-shim/es6-shim.js:1716:18
      at Object._onImmediate (node_modules/es6-shim/es6-shim.js:1689:26)
```

**Comment by 4rzael** [comment]
Okay, I just reduced the bug-case, and it's very strange:

When I try to encode+decode this, it works:

``` js
    var trajectories = 
    [ [ { date: new Date('Thu Nov 19 2015 16:56:30 GMT+0000 (UTC)'),
          signal_strength: -25 } ],
      [ { date: new Date('Thu Nov 19 2015 16:56:30 GMT+0000 (UTC)'),
          signal_strength: -25 } ],
      [ { date: new Date('Thu Nov 19 2015 16:56:30 GMT+0000 (UTC)'),
          signal_strength: -25 } ],
      [ { date: new Date('Thu Nov 19 2015 16:56:30 GMT+0000 (UTC)'),
          signal_strength: -25 } ],
      [ { date: new Date('Thu Nov 19 2015 16:56:30 GMT+0000 (UTC)'),
          signal_strength: -25 } ],
      [ { date: new Date('Thu Nov 19 2015 16:56:30 GMT+0000 (UTC)'),
          signal_strength: -25 } ],
      [ { date: new Date('Thu Nov 19 2015 16:56:30 GMT+0000 (UTC)'),
          signal_strength: -25 } ],
      [ { date: new Date('Thu Nov 19 2015 16:56:30 GMT+0000 (UTC)'),
          signal_strength: -25 } ] ];
```

But when I add one more trajectory (8 -> 9), it crashes:

```
     Error: Groups are not supported
      at skip (node_modules/protocol-buffers/compile.js:21:11)
      at Object.decode (eval at <anonymous> (node_modules/protocol-buffers/node_modules/generate-function/index.js:55:21), <anonymous>:31:16)
      at trajectories/decode.js:17:50
      at new Promise (node_modules/es6-shim/es6-shim.js:1759:9)
      at Object.decode (trajectories/decode.js:16:12)
      at tests/trajectories/general-test.js:279:34
      at node_modules/es6-shim/es6-shim.js:1716:18
      at Object._onImmediate (node_modules/es6-shim/es6-shim.js:1689:26)
```

I looked at my delta-encoded object (the last step before protobuffing), here is what it looks like:

With 8 trajectories:

``` js
deltad: [ { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> } ]
```

And with 9:

``` js
deltad: [ { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> },
  { dates: <Buffer 71 15 a1>, signal_strengths: <Buffer 91> } ]
```

So it looks like the problem comes from protobuf

**Comment by vallettea** [comment]
@DavidBruant may you have a look ?

**Comment by 4rzael** [comment]
##### As seen in [the documentation](https://developers.google.com/protocol-buffers/docs/encoding)

> Only repeated fields of primitive numeric types (types which use the varint, 32-bit, or 64-bit wire types) can be declared "packed".
